package com.pojo;
// Generated Apr 18, 2018 1:05:02 AM by Hibernate Tools 4.3.1



/**
 * Loan generated by hbm2java
 */
public class Loan  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String gender;
     private String email;
     private String date;
     private Double amount;
     private Double interest;
     private Double tamount;

    public Loan() {
    }

    public Loan(String name, String gender, String email, String date, Double amount, Double interest, Double tamount) {
       this.name = name;
       this.gender = gender;
       this.email = email;
       this.date = date;
       this.amount = amount;
       this.interest = interest;
       this.tamount = tamount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Double getInterest() {
        return this.interest;
    }
    
    public void setInterest(Double interest) {
        this.interest = interest;
    }
    public Double getTamount() {
        return this.tamount;
    }
    
    public void setTamount(Double tamount) {
        double a=amount;
        double b=(a*interest)/100;
        double c=a+b;
        tamount=c;
        this.tamount = tamount;
    }




}


