package com.pojo;
// Generated Apr 18, 2018 1:05:02 AM by Hibernate Tools 4.3.1



/**
 * Withdraw generated by hbm2java
 */
public class Withdraw  implements java.io.Serializable {


     private Integer sid;
     private Integer accNo;
     private String name;
     private String accType;
     private Double wamount;
     private Double tamount;

    public Withdraw() {
    }

    public Withdraw(Integer accNo, String name, String accType, Double wamount, Double tamount) {
       this.accNo = accNo;
       this.name = name;
       this.accType = accType;
       this.wamount = wamount;
       this.tamount = tamount;
    }
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public Integer getAccNo() {
        return this.accNo;
    }
    
    public void setAccNo(Integer accNo) {
        this.accNo = accNo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAccType() {
        return this.accType;
    }
    
    public void setAccType(String accType) {
        this.accType = accType;
    }
    public Double getWamount() {
        return this.wamount;
    }
    
    public void setWamount(Double wamount) {
        this.wamount = wamount;
    }
    public Double getTamount() {
        return this.tamount;
    }
    
    public void setTamount(Double tamount) {
        this.tamount = tamount;
    }




}


